//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernRoute.WildData.Npgsql.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernRoute.WildData.Npgsql.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary expression type {0} is not supported..
        /// </summary>
        internal static string BinaryExpressionTypeIsNotSupproted {
            get {
                return ResourceManager.GetString("BinaryExpressionTypeIsNotSupproted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot associate foreign transaction with session..
        /// </summary>
        internal static string CannotAssociateForeignTransactionWithSession {
            get {
                return ResourceManager.GetString("CannotAssociateForeignTransactionWithSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant type {0} is not supported..
        /// </summary>
        internal static string ConstantTypeIsNotSupprted {
            get {
                return ResourceManager.GetString("ConstantTypeIsNotSupprted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting to type {0} is not supported..
        /// </summary>
        internal static string ConvertingToTypeIsNotSupported {
            get {
                return ResourceManager.GetString("ConvertingToTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exactly one row expected..
        /// </summary>
        internal static string ExactlyOneRowExpected {
            get {
                return ResourceManager.GetString("ExactlyOneRowExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function type {0} is not supported..
        /// </summary>
        internal static string FunctionTypeIsNotSupported {
            get {
                return ResourceManager.GetString("FunctionTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order type {0} is not supported..
        /// </summary>
        internal static string OrderTypeIsNotSupported {
            get {
                return ResourceManager.GetString("OrderTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} is less than zero..
        /// </summary>
        internal static string ParameterIsLessThanZero {
            get {
                return ResourceManager.GetString("ParameterIsLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection type {0} is not supported..
        /// </summary>
        internal static string ProjectionTypeIsNotSupported {
            get {
                return ResourceManager.GetString("ProjectionTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query expression type {0} is not supported..
        /// </summary>
        internal static string QueryExpressionTypeIsNotSupported {
            get {
                return ResourceManager.GetString("QueryExpressionTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select type {0} is not supported..
        /// </summary>
        internal static string SelectTypeIsNotSupported {
            get {
                return ResourceManager.GetString("SelectTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity is not persistent..
        /// </summary>
        internal static string TheEntityIsNotPersistent {
            get {
                return ResourceManager.GetString("TheEntityIsNotPersistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity is persistent..
        /// </summary>
        internal static string TheEntityIsPersistent {
            get {
                return ResourceManager.GetString("TheEntityIsPersistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction has been created in another session..
        /// </summary>
        internal static string TransactionHasBeenCreatedInAnotherSession {
            get {
                return ResourceManager.GetString("TransactionHasBeenCreatedInAnotherSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return type {0} is not supported..
        /// </summary>
        internal static string TypeKindIsNotSupported {
            get {
                return ResourceManager.GetString("TypeKindIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary expression type {0} is not supported..
        /// </summary>
        internal static string UnaryExpressionTypeIsNotSupported {
            get {
                return ResourceManager.GetString("UnaryExpressionTypeIsNotSupported", resourceCulture);
            }
        }
    }
}
