//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernRoute.WildData.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernRoute.WildData.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments and Members collection have different item count..
        /// </summary>
        internal static string ArgumentsAndMemberCollectionHaveDifferentItemCount {
            get {
                return ResourceManager.GetString("ArgumentsAndMemberCollectionHaveDifferentItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one item in collection is null..
        /// </summary>
        internal static string AtLeastOneItemInCollectionIsNull {
            get {
                return ResourceManager.GetString("AtLeastOneItemInCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Average&apos; aggregation is not applicable to type {0}..
        /// </summary>
        internal static string AverageAggregationIsNotApplicableToType {
            get {
                return ResourceManager.GetString("AverageAggregationIsNotApplicableToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary operation {0} is not supported..
        /// </summary>
        internal static string BinaryOperationIsNotSupported {
            get {
                return ResourceManager.GetString("BinaryOperationIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block is not supported..
        /// </summary>
        internal static string BlockIsNotSupported {
            get {
                return ResourceManager.GetString("BlockIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch block is not supported..
        /// </summary>
        internal static string CatchBlockIsNotSupported {
            get {
                return ResourceManager.GetString("CatchBlockIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional is not supported..
        /// </summary>
        internal static string ConditionalBlockIsNotSupported {
            get {
                return ResourceManager.GetString("ConditionalBlockIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant&apos;s type is not expected: {0}. Expected: {1}..
        /// </summary>
        internal static string ConstantTypeIsNotExpected {
            get {
                return ResourceManager.GetString("ConstantTypeIsNotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constant value is null, but null is unexpected..
        /// </summary>
        internal static string ConstantValueIsNullButNullIsUnexpected {
            get {
                return ResourceManager.GetString("ConstantValueIsNullButNullIsUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebugInfo is not supported..
        /// </summary>
        internal static string DebugInfoIsNotSupported {
            get {
                return ResourceManager.GetString("DebugInfoIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default is not supported..
        /// </summary>
        internal static string DefaultIsNotSupported {
            get {
                return ResourceManager.GetString("DefaultIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic is not supported..
        /// </summary>
        internal static string DynamicIsNotSupported {
            get {
                return ResourceManager.GetString("DynamicIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElementInit is not supported in this context..
        /// </summary>
        internal static string ElementInitIsNotSupportedInThisContext {
            get {
                return ResourceManager.GetString("ElementInitIsNotSupportedInThisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension is not supported..
        /// </summary>
        internal static string ExtensionIsNotSupported {
            get {
                return ResourceManager.GetString("ExtensionIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function {1} doesn&apos;t take {0} arguments..
        /// </summary>
        internal static string FunctionDoesntTakeArguments {
            get {
                return ResourceManager.GetString("FunctionDoesntTakeArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto is not supported..
        /// </summary>
        internal static string GotoIsNotSupported {
            get {
                return ResourceManager.GetString("GotoIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is not supported..
        /// </summary>
        internal static string IndexIsNotSupported {
            get {
                return ResourceManager.GetString("IndexIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invocation is not supported..
        /// </summary>
        internal static string InvocationIsNotSupported {
            get {
                return ResourceManager.GetString("InvocationIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label is not supported..
        /// </summary>
        internal static string LabelIsNotSupported {
            get {
                return ResourceManager.GetString("LabelIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label target is not supported..
        /// </summary>
        internal static string LabelTargetIsNotSupported {
            get {
                return ResourceManager.GetString("LabelTargetIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda is not supported in this context..
        /// </summary>
        internal static string LambdaIsNotSupportedInThisContext {
            get {
                return ResourceManager.GetString("LambdaIsNotSupportedInThisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListInit is not supported..
        /// </summary>
        internal static string ListIntIsNotSupported {
            get {
                return ResourceManager.GetString("ListIntIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop is not supported..
        /// </summary>
        internal static string LoopIsNotSupported {
            get {
                return ResourceManager.GetString("LoopIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberAssignment is not supported in this context..
        /// </summary>
        internal static string MemberAssignmentIsNotSupportedInThisContext {
            get {
                return ResourceManager.GetString("MemberAssignmentIsNotSupportedInThisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberBindings is not supported in current context..
        /// </summary>
        internal static string MemberBindingsIsNotSupportedInThisContext {
            get {
                return ResourceManager.GetString("MemberBindingsIsNotSupportedInThisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member binding type {0} is not supported in current context..
        /// </summary>
        internal static string MemberBindingTypeIsNotSupportedInThisContext {
            get {
                return ResourceManager.GetString("MemberBindingTypeIsNotSupportedInThisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberInitExpression is not supported in this context..
        /// </summary>
        internal static string MemberInitExpressionIsNotSupportedInThisContext {
            get {
                return ResourceManager.GetString("MemberInitExpressionIsNotSupportedInThisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member {0} is not mapped to the column..
        /// </summary>
        internal static string MemberIsNotMappedToTheColumn {
            get {
                return ResourceManager.GetString("MemberIsNotMappedToTheColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member {0} is not supported..
        /// </summary>
        internal static string MemberIsNotSupported {
            get {
                return ResourceManager.GetString("MemberIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberListBinding is not supported..
        /// </summary>
        internal static string MemberListBindingIsNotSupported {
            get {
                return ResourceManager.GetString("MemberListBindingIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberMemberBinding is not supported in this context..
        /// </summary>
        internal static string MemberMemberBindingIsNotSupportedInThisContext {
            get {
                return ResourceManager.GetString("MemberMemberBindingIsNotSupportedInThisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Distinct with 1 argument is only supported..
        /// </summary>
        internal static string MethodDistinctWithOneArgIsOnlySupported {
            get {
                return ResourceManager.GetString("MethodDistinctWithOneArgIsOnlySupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method is not supported: {0}.{1}..
        /// </summary>
        internal static string MethodIsNotSupported {
            get {
                return ResourceManager.GetString("MethodIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods OrderBy, OrderByDescending, ThenBy, ThenByDescending with 2 arguments are only supported..
        /// </summary>
        internal static string MethodsOrderByOrderByDescThenByThenByDescWithTwoArgAreOnlySupported {
            get {
                return ResourceManager.GetString("MethodsOrderByOrderByDescThenByThenByDescWithTwoArgAreOnlySupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Array is not supported..
        /// </summary>
        internal static string NewArrayIsNotSupported {
            get {
                return ResourceManager.GetString("NewArrayIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New is not supported in this context..
        /// </summary>
        internal static string NewIsNotSupportedInThisContext {
            get {
                return ResourceManager.GetString("NewIsNotSupportedInThisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No columns found for type {0}..
        /// </summary>
        internal static string NoColumnsFoundForType {
            get {
                return ResourceManager.GetString("NoColumnsFoundForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Lambda with 1 parameter is supported in select clause..
        /// </summary>
        internal static string OnlyLambdaWithOneParameterIsSupportedInSelectClause {
            get {
                return ResourceManager.GetString("OnlyLambdaWithOneParameterIsSupportedInSelectClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Lambda with 1 parameter is supported in where clause..
        /// </summary>
        internal static string OnlyLambdaWithOneParameterIsSupportedInWhereClause {
            get {
                return ResourceManager.GetString("OnlyLambdaWithOneParameterIsSupportedInWhereClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} is less than zero..
        /// </summary>
        internal static string ParameterIsLessThanZero {
            get {
                return ResourceManager.GetString("ParameterIsLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicate {0} does not return boolean value..
        /// </summary>
        internal static string PredicateDoesntReturnBoolValue {
            get {
                return ResourceManager.GetString("PredicateDoesntReturnBoolValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection type {0} is not supported..
        /// </summary>
        internal static string ProjectionTypeIsNotSupported {
            get {
                return ResourceManager.GetString("ProjectionTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuntimeVariables are not supported..
        /// </summary>
        internal static string RuntimeVariablesAreNotSupported {
            get {
                return ResourceManager.GetString("RuntimeVariablesAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack is empty..
        /// </summary>
        internal static string StackIsEmpty {
            get {
                return ResourceManager.GetString("StackIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwitchCase is not supported..
        /// </summary>
        internal static string SwitchCaseIsNotSupported {
            get {
                return ResourceManager.GetString("SwitchCaseIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch is not supported..
        /// </summary>
        internal static string SwitchIsNotSupported {
            get {
                return ResourceManager.GetString("SwitchIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model ignores &apos;{0}&apos; property..
        /// </summary>
        internal static string TheModelIgnoresProperty {
            get {
                return ResourceManager.GetString("TheModelIgnoresProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TryBinary is not supported..
        /// </summary>
        internal static string TryBinaryIsNotSupported {
            get {
                return ResourceManager.GetString("TryBinaryIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try is not supported..
        /// </summary>
        internal static string TryIsNotSupported {
            get {
                return ResourceManager.GetString("TryIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type `{0}` is not supported..
        /// </summary>
        internal static string TypeIsNotSupported {
            get {
                return ResourceManager.GetString("TypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not supported..
        /// </summary>
        internal static string TypeKindIsNotSupported {
            get {
                return ResourceManager.GetString("TypeKindIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to interpretate string as {0} value..
        /// </summary>
        internal static string UnableToInterpretateString {
            get {
                return ResourceManager.GetString("UnableToInterpretateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary operation {0} is not supported..
        /// </summary>
        internal static string UnaryOperationIsNotSupported {
            get {
                return ResourceManager.GetString("UnaryOperationIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected stack size: {0}. Expected: 1..
        /// </summary>
        internal static string UnexpectedStackSize {
            get {
                return ResourceManager.GetString("UnexpectedStackSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected tree element type: {0}. Expected: {1}..
        /// </summary>
        internal static string UnexpectedTreeElementTypeWith1Expected {
            get {
                return ResourceManager.GetString("UnexpectedTreeElementTypeWith1Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected tree element type: {0}. Expected: {1}, {2} or {3}..
        /// </summary>
        internal static string UnexpectedTreeElementTypeWith3Expected {
            get {
                return ResourceManager.GetString("UnexpectedTreeElementTypeWith3Expected", resourceCulture);
            }
        }
    }
}
